import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { BulbFilled, InboxOutlined } from "@ant-design/icons"
import { message, Upload } from "antd"
import { DesktopOutlined, FileOutlined, PieChartOutlined, TeamOutlined, UserOutlined } from "@ant-design/icons"
import { Breadcrumb, Layout, Menu } from "antd"
import { useState } from "react"
import SkinCancer from "../components/skinCancer"
import Pneumonia from "../components/pneumonia"

export default function Home() {
  const [dis,setDis] = useState(1)
  const { Header, Content, Footer, Sider } = Layout
  function getItem(label, key, icon, children) {
    return {
      key,
      icon,
      children,
      label,
    }
  }
  const items = [
    getItem(<strong>Disease Diagnosing platform</strong>, "0", <DesktopOutlined />),
    getItem(<button className={styles.button} onClick={()=>setDis(1)}>Skin cancer detection</button>, "1"),
    getItem(<button className={styles.button} onClick={()=>setDis(2)}>Pneumonia detection</button>, "2"),
  ]

  function select(dis){
    switch(dis){
      case 1 : return <SkinCancer/>
      case 2 : return <Pneumonia/>
    }
  }

  const [collapsed, setCollapsed] = useState(false)
  return (
    <div className={styles.container}>
      <Head>
        <title>Pneumonia detection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Layout
          style={{
            minHeight: "100vh",
            minWidth: "100vw",
          }}
        >
          <Sider
            collapsible
            collapsed={collapsed}
            onCollapse={(value) => setCollapsed(value)}
            className={styles.sider}
            width="30vw"
          >
            <div className="logo" />
            <Menu theme="dark" defaultSelectedKeys={["1"]} mode="inline" items={items}/>
          </Sider>
          <Layout className="site-layout">
            <Header
              className="site-layout-background"
              style={{
                padding: 0,
              }}
            >
              <h1 className={styles.header}>Disease Diagnosing platform</h1>
            </Header>
            <Content
              style={{
                margin: "10px 16px",
              }}
            >
              <div
                className="site-layout-background"
                style={{
                  padding: 24,
                  minHeight: 360,
                }}
              >
                {
                  select(dis)
                }
              </div>
            </Content>
          </Layout>
        </Layout>
      </main>

      <footer className={styles.footer}>
        Made by&nbsp;
        <a href="https://github.com/harshiitsingh" target="_blank" rel="noopener noreferrer">
          Harshit
        </a>
        &nbsp;and&nbsp;
        <a href="https://github.com/oyesaurav" target="_blank" rel="noopener noreferrer">
          Saurav
        </a>

      </footer>
    </div>
  )
}
